#!/usr/bin/env python3
"""
Builds geo-data.js — the ZIP/place table the service-area checker uses to give a
real answer to anyone in western Washington, not just the towns Mikey serves.

Source of truth is GeoNames' US postal export (which is itself derived from the
Census gazetteer). We never type coordinates by hand: a wrong centroid means the
checker tells a customer they're 12 miles away when they're 40, and that is the
kind of thing Mikey finds out about in a driveway.

    python3 tools/build-geo-data.py          # writes geo-data.js at the repo root

Everything within RADIUS_MI of the shop is included. That's wide on purpose —
someone in Tacoma should get "you're 47 miles out, here's what actually works"
rather than a shrug, and the whole payload is still ~10 KB.
"""
import io, math, re, sys, urllib.request, zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "geo-data.js"
SRC = "https://download.geonames.org/export/zip/US.zip"

# Home base — Snohomish, WA 98290. Matches CLAUDE.md and the homepage JSON-LD.
BLAT, BLON = 47.9129, -122.0982
RADIUS_MI = 130
# 0.001 degrees ≈ 111 m of latitude, 74 m of longitude up here. Rounding to that
# grid costs us at most ~0.04 miles, which is invisible in "you're 31 miles out".
GRID = 1000
OFFSET = 4000          # keeps the encoded deltas positive
B36 = "0123456789abcdefghijklmnopqrstuvwxyz"


def b36(n, width):
    s = ""
    while n:
        s = B36[n % 36] + s
        n //= 36
    s = s.rjust(width, "0")
    if len(s) > width:
        sys.exit(f"value {n} does not fit in {width} base-36 chars")
    return s


def miles(lat, lon):
    dy = (lat - BLAT) * 69.05
    dx = (lon - BLON) * 69.05 * math.cos(math.radians(BLAT))
    return math.hypot(dy, dx)


def fetch():
    cache = ROOT / "tools" / ".geonames-us.zip"
    if cache.exists():
        return cache.read_bytes()
    print(f"downloading {SRC} …")
    data = urllib.request.urlopen(SRC, timeout=120).read()
    cache.write_bytes(data)
    return data


def main():
    raw = zipfile.ZipFile(io.BytesIO(fetch())).read("US.txt").decode("utf-8")

    rows = []
    for line in raw.splitlines():
        f = line.split("\t")
        if len(f) < 11 or f[4] != "WA":
            continue
        zc, place = f[1].strip(), f[2].strip()
        try:
            lat, lon = float(f[9]), float(f[10])
        except ValueError:
            continue
        if not re.fullmatch(r"\d{5}", zc) or miles(lat, lon) > RADIUS_MI:
            continue
        rows.append((zc, place, lat, lon))

    rows.sort()
    # One ZIP can appear more than once in the export; first row wins.
    seen, uniq = set(), []
    for r in rows:
        if r[0] in seen:
            continue
        seen.add(r[0])
        uniq.append(r)

    names, idx = [], {}
    for _, place, _, _ in uniq:
        if place not in idx:
            idx[place] = len(names)
            names.append(place)

    recs = []
    for zc, place, lat, lon in uniq:
        dlat = round((lat - BLAT) * GRID) + OFFSET
        dlon = round((lon - BLON) * GRID) + OFFSET
        recs.append(zc + b36(dlat, 3) + b36(dlon, 3) + b36(idx[place], 2))

    payload = "".join(recs)
    joined = "|".join(names)
    if "|" in "".join(names):
        sys.exit("a place name contains the record separator")

    OUT.write_text(
        "/* GENERATED by tools/build-geo-data.py — do not hand-edit.\n"
        f"   {len(uniq)} Washington ZIPs within {RADIUS_MI} miles of "
        f"{BLAT},{BLON}, from GeoNames.\n"
        "   Each 13-char record is ZIP(5) + lat delta(3) + lon delta(3) + name index(2),\n"
        f"   base 36, offset {OFFSET}, in units of 1/{GRID} degree. */\n"
        "window.MIKEY_GEO = {\n"
        f"  base: [{BLAT}, {BLON}], grid: {GRID}, offset: {OFFSET},\n"
        f'  names: "{joined}",\n'
        f'  zips: "{payload}"\n'
        "};\n",
        encoding="utf-8",
    )
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(ROOT)} — {len(uniq)} ZIPs, "
          f"{len(names)} place names, {kb:.1f} KB")


if __name__ == "__main__":
    main()
